### ISSUE TITLE
Icons are huge on iOS

### ISSUE THREAD

**Issue by thomasdewulf** [fosopenscouting/saamdagen#132]

**Comment by JannesVanWonterghem** [comment]
@thomasdewulf, geen issue meer? Vermoed dat het nog open staat van vorig jaar, maar al is opgelost
![image2](https://user-images.githubusercontent.com/36441142/185981870-8ba9035e-d557-4912-a122-083137c31257.png)
![image1](https://user-images.githubusercontent.com/36441142/185981872-a226fa42-3746-4289-a02f-7db384d7c789.png)
![image0 (1)](https://user-images.githubusercontent.com/36441142/185981876-27bcc49f-0e93-420a-a485-1f707c139be1.png)
?

**Comment by thomasdewulf** [comment]
Aha, mogelijks opgelost door Expo update, nice!
