### ISSUE TITLE
SafeArea niet gerespecteerd, zelf fix voorzien

### ISSUE THREAD

**Issue by TijlS** [fosopenscouting/saamdagen#284]
Tijdens het gebruik van de app heb ik gezien dat de SafeArea niet gerespecteerd wordt, zoals te zien is op onderstaande screenshots.
_(Motorola Edge 30 Fusion, Android 13)_

<img src="https://github.com/user-attachments/assets/a089275e-fa38-46dc-988d-b08eea3141e4" height="500" />
<img src="https://github.com/user-attachments/assets/7c18b253-ca56-4271-8a6c-d7fc4db412bc" height="500" />

Toen ik de repo gevonden had, dacht ik "ik zal zelf eens kijken of ik dit kan oplossen :)", en ik heb dit ook kunnen doen 🎉.
Ik heb daarbij ook wat (in mijn ogen toch) kleine 'verbeteringen' gedaan (dependencies upgraden, Material 3, ...). Als het ok is voor jullie zou ik deze graag eens willen tonen. (video en/of apk) 
Laat maar weten!

Tijl

  _(PS: sorry als de titel niet zo duidelijk is 🙃)_

**Comment by thomasdewulf** [comment]
Hey Tijl, zalig! Je mag sowieso een pull request maken als je wil. We kijken er dan sowieso eens naar, maar we nemen binnenkort allesinds contact op ook!

**Comment by TijlS** [comment]
Ik heb ook gezien dat er steeds een error verscheen: 'Multiple elements with same key found'. (Zorgt ook dat de 2 accordions tegelijk open- en dichtgaan)

Dit heb ik kunnen terugleiden naar 2x dezelfde `volgorde` bij de Saamdagen-App-Inhoud: [/Programma/Zaterdag/15-za-kampvuur.md](https://github.com/fosopenscouting/Saamdagen-App-inhoud/blob/main/Production/Programma/Zaterdag/15-za-kampvuur.md) en  [/Production/Programma/Zaterdag/16-za-snack.md ](https://github.com/fosopenscouting/Saamdagen-App-inhoud/blob/main/Production/Programma/Zaterdag/16-za-snack.md), nl. `16`.

Moet ik daar ook een PR voor maken?

**Comment by thomasdewulf** [comment]
> Ik heb ook gezien dat er steeds een error verscheen: 'Multiple elements with same key found'. (Zorgt ook dat de 2 accordions tegelijk open- en dichtgaan)
> 
> Dit heb ik kunnen terugleiden naar 2x dezelfde `volgorde` bij de Saamdagen-App-Inhoud: [/Programma/Zaterdag/15-za-kampvuur.md](https://github.com/fosopenscouting/Saamdagen-App-inhoud/blob/main/Production/Programma/Zaterdag/15-za-kampvuur.md) en [/Production/Programma/Zaterdag/16-za-snack.md ](https://github.com/fosopenscouting/Saamdagen-App-inhoud/blob/main/Production/Programma/Zaterdag/16-za-snack.md), nl. `16`.
> 
> Moet ik daar ook een PR voor maken?

De stafmedewerker voor Saamdagen brengt dat in orde :)

**Comment by thomasdewulf** [comment]
Merged :)
