### ISSUE TITLE
Nieuwe UI programma

### ISSUE THREAD

**Issue by TijlS** [fosopenscouting/saamdagen#291]
Zou het leuk zijn om de tijdlijn te updaten naar het volgende?

<img src="https://github.com/user-attachments/assets/ae6d3ee0-f45d-42ed-91a4-30e25b6c4855" height="500" />

Het rood _(of eender welk ander kleur)_ zou bv gebruikt kunnen worden om 'belangrijke' dingen aan te duiden.

**Comment by thomasdewulf** [comment]
Ik ben alvast fan! Is het heel lastig om hierin meteen te kijken naar #149 (auto scroll naar current time)

**Comment by TijlS** [comment]
Zal eens kijken of dit lukt.

**Comment by Beramos** [comment]
Vet!
