### ISSUE TITLE
Splashscreen klopt niet

### ISSUE THREAD

**Issue by TijlS** [fosopenscouting/saamdagen#293]
![Screenshot_20241118-132542.png](https://github.com/user-attachments/assets/8d95a08e-2023-44bf-ad15-cb9c2678ff52)

**Comment by TijlS** [comment]
Kan iemand bevestigen dat dit op iOS ook zo is?

**Comment by thomasdewulf** [comment]
Yes :'(

**Comment by TijlS** [comment]
Raar, in de Expo Go-app toont het wel zoals het zou moeten...
-> @thomasdewulf Werkt het op iOS ook via de Expo Go-app?

**Comment by TijlS** [comment]
Heh? En op Android werkt het dan weer wel?

![Uploading Screenshot_20241118-191039.png …]()
