### ISSUE TITLE
Programma raadplegen

### ISSUE THREAD

**Issue by thomasdewulf** [fosopenscouting/saamdagen#80]
Een deelnemer kan het programma van Saamdagen raadplegen

Verder uit te werken:
- Welke informatie is beschikbaar
- Hoe wordt de informatie beheerd

**Comment by NuclearCookie** [comment]
https://github.com/wix/react-native-calendars#agenda
https://github.com/thegamenicorus/react-native-timeline-listview
https://github.com/hoangnm/react-native-week-view

**Comment by NuclearCookie** [comment]
https://github.com/Eugnis/react-native-timeline-flatlist
This one seems to work with Expo.

I can see this work with a timeline view per location, with tabs. 

e.g:

Tabs 
Friday | Saturday | Sunday
Subtabs
Outside | Party tent | Quiet area | ... 

Each with their own schedule.

**Comment by NuclearCookie** [comment]
Scrap that.

Not using any specific module for this.
GOt it to work nicely with just the collapsible package and manually listing data.
